# Generated by Django 2.1.1 on 2018-11-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
