# Generated by Django 2.1.1 on 2019-03-04 13:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
