# Generated by Django 2.1.1 on 2019-03-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0002_auto_20190304_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='question',
            field=models.TextField(),
        ),
    ]
