# Generated by Django 2.1.1 on 2019-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0003_auto_20190304_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anxietyscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Scale',
        ),
    ]
