# Generated by Django 2.1.1 on 2019-03-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0006_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='性别'),
        ),
    ]
