# Generated by Django 2.1.1 on 2019-03-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0008_auto_20190318_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('number', models.CharField(max_length=20, verbose_name='学号')),
            ],
        ),
    ]
