# Generated by Django 2.1.1 on 2019-03-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0009_stuinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuinfo',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterModelTable(
            name='stuinfo',
            table='stuinfo',
        ),
    ]
