# Generated by Django 2.1.1 on 2019-03-19 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0011_auto_20190319_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anxietyscale',
            options={'verbose_name': '贝克抑郁', 'verbose_name_plural': '贝克抑郁'},
        ),
    ]
