# Generated by Django 2.1.1 on 2019-03-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0012_auto_20190319_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anxietyscale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='depressionscale',
            options={'verbose_name': '贝克抑郁', 'verbose_name_plural': '贝克抑郁'},
        ),
        migrations.RemoveField(
            model_name='anxietyscale',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='anxietyscale',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='anxietyscale',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='anxietyscale',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='depressionscale',
            name='question',
        ),
        migrations.AddField(
            model_name='anxietyscale',
            name='question',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depressionscale',
            name='question1',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depressionscale',
            name='question2',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depressionscale',
            name='question3',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depressionscale',
            name='question4',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='anxietyscale',
            table=None,
        ),
        migrations.AlterModelTable(
            name='depressionscale',
            table='depressionscale',
        ),
    ]
