# Generated by Django 2.1.1 on 2019-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0013_auto_20190319_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': '大学生人格问卷',
                'verbose_name_plural': '大学生人格问卷',
                'db_table': 'upi',
            },
        ),
    ]
