# Generated by Django 2.1.1 on 2019-03-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0015_auto_20190319_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepressionGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.UserInfo')),
            ],
            options={
                'verbose_name': '贝克抑郁分数',
                'verbose_name_plural': '贝克抑郁分数',
                'db_table': 'depressiongrade',
            },
        ),
    ]
