# Generated by Django 2.1.1 on 2019-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0016_depressiongrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depressiongrade',
            name='time',
            field=models.CharField(max_length=300),
        ),
    ]
