# Generated by Django 2.1.1 on 2019-03-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0017_auto_20190320_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depressiongrade',
            name='time',
            field=models.TextField(max_length=500),
        ),
    ]
