# Generated by Django 2.1.1 on 2019-03-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0018_auto_20190321_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpiGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('time', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=10)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.UserInfo')),
            ],
            options={
                'verbose_name': 'UPI分数',
                'verbose_name_plural': 'UPI分数',
                'db_table': 'upigrade',
            },
        ),
    ]
