# Generated by Django 2.1.1 on 2019-03-22 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0019_upigrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCLGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('average', models.FloatField()),
                ('t_score', models.CharField(max_length=50)),
                ('factor', models.FloatField()),
                ('yang', models.IntegerField()),
                ('yin', models.IntegerField()),
                ('yang_average', models.FloatField()),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychology.UserInfo')),
            ],
            options={
                'verbose_name': 'SCL90分数',
                'verbose_name_plural': 'SCL90分数',
                'db_table': 'scl90grade',
            },
        ),
        migrations.AlterField(
            model_name='depressiongrade',
            name='time',
            field=models.TextField(),
        ),
    ]
