# Generated by Django 2.1.1 on 2019-03-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0020_auto_20190322_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='sclgrade',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sclgrade',
            name='time',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
