# Generated by Django 2.1.1 on 2019-03-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0021_auto_20190322_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sclgrade',
            name='t_score',
            field=models.CharField(max_length=100),
        ),
    ]
